#!/bin/bash
# Structural Synchronization Tool
# Automatically updates documentation to match current repository structure

set -euo pipefail

# Script directory detection
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$REPO_ROOT"

# Utility functions
log_info() {
    echo "ℹ️  $*"
}

log_success() {
    echo "✅ $*"
}

log_error() {
    echo "❌ $*" >&2
}

log_warning() {
    echo "⚠️  $*" >&2
}

# Only show header when running as main script (not when generating tree)
if [[ "${1:-sync}" != "--generate-tree" ]]; then
    echo "🔄 REPOSITORY STRUCTURE SYNCHRONIZATION"
    echo "========================================"
fi

# Generate comprehensive PROJECT-STRUCTURE.md file
generate_project_structure_file() {
    local structure_file="$REPO_ROOT/docs/PROJECT-STRUCTURE.md"
    local timestamp
    timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
    
    log_info "Generating canonical PROJECT-STRUCTURE.md file..."
    
    cat > "$structure_file" << 'EOF'
# Project Structure

> **Single Source of Truth**: This file is the canonical reference for the soft-delete project structure. All documentation structure sections are synchronized from this file.
> 
> **Auto-generated by sync-structure.sh** - Do not edit manually. Changes will be overwritten during synchronization.

## Directory Tree

EOF
    
    # Generate the tree structure
    generate_directory_tree >> "$structure_file"
    
    cat >> "$structure_file" << 'EOF'

## Structure Guidelines

### File Organization Principles

1. **Configuration at Root**: Primary configuration files (`.editorconfig`, `.gitignore`, etc.) remain at project root
2. **Documentation Hierarchy**: 
   - Technical docs in `docs/` directory
   - Warp AI context in `.warp/` directory
   - Project overview in root `README.md`
3. **Script Organization**: All utility scripts in `scripts/` directory with clear naming
4. **Test Structure**: All tests in `tests/` directory using BATS framework
5. **Build Artifacts**: Compiled binaries in `bin/`, distribution files in `dist/`

### Directory Purposes

- **`.github/`**: GitHub-specific configuration and workflows
- **`.warp/`**: AI agent configuration and development protocols
- **`bin/`**: Compiled executable binaries
- **`docs/`**: Comprehensive technical documentation
- **`examples/`**: Usage examples and demonstrations
- **`scripts/`**: Development and maintenance utilities
- **`tests/`**: Test suites and testing infrastructure

### Validation Requirements

- All scripts must be documented in API.md
- Cross-references must be valid and up-to-date
- File counts must match actual repository state
- Executable references must use correct naming conventions

EOF
    
    echo "*Last Updated: $timestamp*" >> "$structure_file"
    
    log_success "Generated PROJECT-STRUCTURE.md with $(wc -l < "$structure_file") lines"
    return 0
}

# Generate complete directory tree showing ALL files and directories for transparency
generate_directory_tree() {
    # Generate complete tree structure for full transparency
    echo '```'
    echo "soft-delete/"
    
    # Use a comprehensive approach to show ALL files and directories
    # First pass: show all entries with proper tree formatting
    generate_complete_tree_structure "." "" "false"
    
    echo '```'
}

# Helper function to recursively generate complete tree structure
generate_complete_tree_structure() {
    local current_dir="$1"
    local prefix="$2"
    local is_last="$3"
    
    # Skip .git directory for readability but include everything else
    if [[ "$(basename "$current_dir")" == ".git" ]]; then
        return
    fi
    
    # Get all entries (files and directories) sorted
    local entries=()
    while IFS= read -r -d '' entry; do
        entries+=("$entry")
    done < <(find "$current_dir" -maxdepth 1 -mindepth 1 ! -name ".git" -print0 | sort -z)
    
    local entry_count=${#entries[@]}
    local current_index=0
    
    for entry in "${entries[@]}"; do
        current_index=$((current_index + 1))
        local basename_entry
        basename_entry=$(basename "$entry")
        local is_last_entry="false"
        
        if [[ $current_index -eq $entry_count ]]; then
            is_last_entry="true"
        fi
        
        # Determine tree characters
        local tree_char="├──"
        local next_prefix="$prefix│   "
        
        if [[ "$is_last_entry" == "true" ]]; then
            tree_char="└──"
            next_prefix="$prefix    "
        fi
        
        # Generate description based on file/directory type and name
        local description
        description=$(generate_file_description "$entry")
        
        if [[ -d "$entry" ]]; then
            echo "$prefix$tree_char $basename_entry/$description"
            # Recursively process subdirectory
            generate_complete_tree_structure "$entry" "$next_prefix" "$is_last_entry"
        else
            echo "$prefix$tree_char $basename_entry$description"
        fi
    done
}

# Generate intelligent descriptions for files and directories
generate_file_description() {
    local entry="$1"
    local basename_entry
    basename_entry=$(basename "$entry")
    local description=""
    
    # Directory descriptions
    if [[ -d "$entry" ]]; then
        case "$basename_entry" in
            ".github") description="                 # GitHub configuration and workflows" ;;
            "workflows") description="               # GitHub Actions workflows" ;;
            ".warp") description="                   # Warp.dev AI configuration and context" ;;
            "protocols") description="               # Development protocols and procedures" ;;
            "rules") description="                   # AI agent behavioral rules" ;;
            "templates") description="               # Template files for rules and protocols" ;;
            "bin") description="                     # Compiled executable binaries" ;;
            "dist") description="                    # Distribution and build artifacts" ;;
            "docs") description="                    # Comprehensive project documentation" ;;
            "examples") description="                # Usage examples and demonstrations" ;;
            "Formula") description="                  # Package manager formulas (Homebrew)" ;;
            "reports") description="                 # Test reports and analysis artifacts" ;;
            "scripts") description="                 # Utility and automation scripts" ;;
            "tests") description="                   # Test suites and testing infrastructure" ;;
            *) description="" ;;
        esac
    else
        # File descriptions based on extension and name
        case "$basename_entry" in
            # Configuration files
            ".editorconfig") description="            # Code formatting and editor standards" ;;
            ".gitattributes") description="           # Git file handling configuration" ;;
            ".gitignore") description="               # Git ignore patterns and exclusions" ;;
            ".markdownlint.yaml") description="       # Markdown linting rules and configuration" ;;
            ".shellcheckrc") description="            # Shell script linting configuration" ;;
            
            # GitHub workflows
            "release.yml") description="              # GitHub Actions CI/CD release pipeline" ;;
            
            # Documentation files
            "README.md") description="                # Project overview and main documentation" ;;
            "API.md") description="                   # Comprehensive API reference documentation" ;;
            "DEPLOYMENT.md") description="            # Deployment procedures and automation guide" ;;
            "SECURITY.md") description="              # Security policies and vulnerability reporting" ;;
            "TESTING.md") description="               # Testing procedures and infrastructure guide" ;;
            "CHANGELOG.md") description="             # Version history and change tracking" ;;
            "CONTRIBUTING.md") description="          # Contribution guidelines and development setup" ;;
            "project-context.md") description="       # Main project context for AI assistance" ;;
            
            # Container and deployment files
            "docker-compose.test.yml") description="  # Docker testing environment configuration" ;;
            "Dockerfile.runtime") description="       # Runtime container image definition" ;;
            "Dockerfile.test") description="          # Testing container image definition" ;;
            
            # Build and automation files
            "Makefile") description="                 # Build automation and development tasks" ;;
            "install.sh") description="               # Installation script for end users" ;;
            
            # Legal and version files
            "LICENSE") description="                  # MIT License terms and conditions" ;;
            "VERSION") description="                  # Current version information" ;;
            
            # Main application files
            "soft-delete.sh") description="           # Main application source script" ;;
            "soft-delete") description="              # Compiled executable binary" ;;
            
            # Script files (with intelligent descriptions)
            "benchmark.sh") description="             # Performance testing and benchmarking" ;;
            "changelog.sh") description="             # Automated changelog generation" ;;
            "check-duplicates.sh") description="      # Duplicate content detection and cleanup" ;;
            "checkpoint.sh") description="            # Development checkpoint and backup utility" ;;
            "cleanup.sh") description="               # Comprehensive system cleanup utility" ;;
            "compliance-check.sh") description="      # 100% compliance verification system" ;;
            "deploy.sh") description="                # Deployment automation and orchestration" ;;
            "document-update.sh") description="       # Documentation update automation" ;;
            "duplicate-finder.sh") description="      # Advanced duplicate file detection" ;;
            "generate-docs.sh") description="         # Documentation generation automation" ;;
            "package.sh") description="               # Package creation and distribution" ;;
            "release.sh") description="               # Release management and versioning" ;;
            "run-tests.sh") description="             # Docker-based comprehensive test runner" ;;
            "security-scan.sh") description="         # Security vulnerability scanning" ;;
            "sync-structure.sh") description="        # Project structure synchronization" ;;
            "validate-structure.sh") description="    # Project structure validation" ;;
            
            # Test files
            "edge-cases.bats") description="          # Edge case and boundary testing suite" ;;
            "soft-delete.bats") description="         # Main application test suite" ;;
            "test_helper.bash") description="         # Test utilities and helper functions" ;;
            
            # Example files
            "basic_usage.sh") description="           # Basic usage examples and tutorials" ;;
            "advanced_usage.sh") description="        # Advanced integration examples" ;;
            
            # Package files
            "soft-delete.rb") description="           # Homebrew formula for package distribution" ;;
            
            # Hidden files
            ".gitkeep") description="                 # Git directory preservation marker" ;;
            
            # Protocol and rule files (dynamically described)
            *.md)
                if [[ "$entry" == *"/protocols/"* ]]; then
                    description="                # Development protocol specification"
                elif [[ "$entry" == *"/rules/"* ]]; then
                    description="                    # AI agent behavioral rule definition"
                else
                    description="                        # Markdown documentation file"
                fi
                ;;
            
            # Programming files
            *.sh) description="                       # Shell script" ;;
            *.py) description="                       # Python script" ;;
            *.js) description="                       # JavaScript file" ;;
            *.ts) description="                       # TypeScript file" ;;
            *.json) description="                     # JSON configuration or data file" ;;
            *.yaml|*.yml) description="               # YAML configuration file" ;;
            *.toml) description="                     # TOML configuration file" ;;
            *.xml) description="                      # XML data or configuration file" ;;
            
            # Default for unknown files
            *) 
                if [[ -x "$entry" ]]; then
                    description="                     # Executable file"
                else
                    description=""
                fi
                ;;
        esac
    fi
    
    echo "$description"
}

# Check for duplicate structure sections
check_for_duplicates() {
    local file="$1"
    local duplicates=0
    
    # Count occurrences of structure indicators
    local structure_count
    structure_count=$(grep -c "soft-delete/" "$file" 2>/dev/null || echo 0)
    
    # Check for multiple code blocks with soft-delete/
    if [[ $structure_count -gt 1 ]]; then
        log_error "DUPLICATE DETECTED: Found $structure_count structure sections in $file"
        duplicates=$structure_count
    fi
    
    # Check for sync header duplication
    local header_count
    header_count=$(grep -c "🔄 REPOSITORY STRUCTURE SYNCHRONIZATION" "$file" 2>/dev/null || echo 0)
    if [[ $header_count -gt 0 ]]; then
        log_error "SYNC HEADER CONTAMINATION: Found sync headers in $file (should not exist)"
        duplicates=$((duplicates + header_count))
    fi
    
    if [[ $duplicates -gt 0 ]]; then
        return 1
    else
        return 0
    fi
}

# Clean existing duplicate structures
clean_duplicates() {
    local file="$1"
    local temp_file
    temp_file=$(mktemp)
    
    log_info "Cleaning any existing duplicates in $file..."
    
    # Remove sync headers that shouldn't be in the file
    sed '/🔄 REPOSITORY STRUCTURE SYNCHRONIZATION/d; /========================================/d' "$file" > "$temp_file"
    mv "$temp_file" "$file"
    
    # Remove duplicate structure sections (keep only the first one)
    local temp_file2
    temp_file2=$(mktemp)
    
    awk '
    BEGIN { structure_found = 0; in_structure = 0; skip_structure = 0 }
    
    # Detect start of structure section
    /^#+ (Project|Directory) Structure$/ {
        if (structure_found == 0) {
            structure_found = 1
            print $0
            next
        } else {
            # This is a duplicate - skip entire section
            skip_structure = 1
            next
        }
    }
    
    # Handle content within structure sections
    structure_found == 1 && !skip_structure {
        if (/^```/) {
            if (in_structure == 0) {
                in_structure = 1
                print $0
                next
            } else {
                in_structure = 0
                structure_found = 2  # Mark as completed
                print $0
                next
            }
        }
        if (in_structure == 1 || /^$/) {
            print $0
            next
        }
        if (/^#+ /) {
            structure_found = 2  # End of structure section
            print $0
            next
        }
        print $0
        next
    }
    
    # Skip duplicate structure content
    skip_structure == 1 {
        if (/^#+ / && !/^#+ (Project|Directory) Structure$/) {
            skip_structure = 0
            print $0
        }
        next
    }
    
    # Print all other lines
    { print }
    ' "$file" > "$temp_file2"
    
    mv "$temp_file2" "$file"
    log_success "Cleaned duplicates from $file"
}

# Update file listings in documentation using canonical source
update_file_listings() {
    local file="$1"
    local structure_file="$REPO_ROOT/docs/PROJECT-STRUCTURE.md"
    local temp_file
    temp_file=$(mktemp)
    
    log_info "Updating file listings in $file using canonical source..."
    
    # Ensure PROJECT-STRUCTURE.md exists and is up-to-date
    if [[ ! -f "$structure_file" ]]; then
        log_warning "PROJECT-STRUCTURE.md not found, generating it first"
        generate_project_structure_file
    fi
    
    # First, check for and clean any duplicates
    check_for_duplicates "$file"
    local duplicate_check=$?
    if [[ $duplicate_check -ne 0 ]]; then
        clean_duplicates "$file"
    fi
    
    # Extract just the tree structure from PROJECT-STRUCTURE.md
    local canonical_tree
    canonical_tree=$(sed -n '/^```$/,/^```$/p' "$structure_file")
    
    # Look for sections that need updating
    if grep -q "# Project Structure\|# Directory Structure\|## Project Structure\|## Directory Structure" "$file"; then
        
        # Use Python for more reliable regex replacement
        python3 - "$file" "$structure_file" << 'PYTHON_END' > "$temp_file"
import re
import sys

if len(sys.argv) < 3:
    print("Error: insufficient arguments", file=sys.stderr)
    sys.exit(1)

# Read the target file
try:
    with open(sys.argv[1], 'r') as f:
        content = f.read()
except FileNotFoundError:
    print("Error: target file not found", file=sys.stderr)
    sys.exit(1)

# Read the canonical tree structure
try:
    with open(sys.argv[2], 'r') as f:
        structure_content = f.read()
except FileNotFoundError:
    print("Error: structure file not found", file=sys.stderr)
    sys.exit(1)

# Extract just the tree part
tree_pattern = r'^' + re.escape('```') + r'\n(.*?)^' + re.escape('```')
tree_match = re.search(tree_pattern, structure_content, re.MULTILINE | re.DOTALL)
if tree_match:
    canonical_tree = '```\n' + tree_match.group(1) + '```'
else:
    canonical_tree = '```\nsoft-delete/\n(structure extraction failed)\n```'

# Pattern to match structure sections
pattern_str = r'^(#+\s+(?:Project|Directory)\s+Structure)\s*$\n\n.*?^' + re.escape('```') + r'\n.*?^' + re.escape('```')

# Replace with canonical structure
def replace_structure(match):
    header = match.group(1)
    return header + '\n\n' + canonical_tree

# Perform replacement
result = re.sub(pattern_str, replace_structure, content, flags=re.MULTILINE | re.DOTALL)

# Output result
print(result, end='')
PYTHON_END
        
        if [[ -s "$temp_file" ]]; then
            mv "$temp_file" "$file"
            log_success "Updated structure in $file from canonical source"
        else
            rm "$temp_file"
            log_error "Failed to update $file"
        fi
    else
        rm -f "$temp_file"
    fi
}

# Update script references in documentation
update_script_references() {
    local file="$1"
    local temp_file
    temp_file=$(mktemp)
    
    log_info "Validating script references in $file..."
    
    # Find all script references and check if they exist
    local script_refs
    script_refs=$(grep -o 'scripts/[a-zA-Z0-9_-]*\.sh' "$file" 2>/dev/null || true)
    
    local updates_needed=false
    if [[ -n "$script_refs" ]]; then
        while IFS= read -r script_ref; do
            if [[ ! -f "$script_ref" ]]; then
                log_warning "Referenced script missing: $script_ref"
                updates_needed=true
            fi
        done <<< "$script_refs"
    fi
    
    if [[ "$updates_needed" == "true" ]]; then
        log_warning "Script references in $file need manual review"
    fi
    
    rm -f "$temp_file"
}

# Preserve existing API documentation (do not regenerate)
preserve_api_docs() {
    log_info "Preserving existing API documentation..."
    
    if [[ -f "docs/API.md" ]]; then
        log_success "API documentation exists and is preserved"
        log_info "Note: API.md contains comprehensive technical documentation"
        log_info "      and should be manually maintained by developers"
    else
        log_warning "API documentation file (docs/API.md) not found"
        log_info "Consider creating comprehensive API documentation"
    fi
}

# Update version references across all files
sync_version_references() {
    if [[ ! -f "VERSION" ]]; then
        log_warning "VERSION file not found, skipping version sync"
        return 0
    fi
    
    local version
    version=$(tr -d '\n\r' < VERSION | tr -d ' ')
    
    log_info "Synchronizing version $version across all files..."
    
    # Update README.md badge
    if [[ -f "README.md" ]]; then
        if grep -q "badge/version-" "README.md"; then
            sed -i "s|badge/version-[^-]*-blue|badge/version-$version-blue|g" "README.md"
            log_success "Updated version badge in README.md"
        fi
    fi
    
    # Update other version references as needed
    local doc_files=()
    if [[ -d "docs" ]]; then
        while IFS= read -r -d '' file; do
            doc_files+=("$file")
        done < <(find docs/ -name "*.md" -type f -print0)
    fi
    if [[ -d ".warp" ]]; then
        while IFS= read -r -d '' file; do
            doc_files+=("$file")
        done < <(find .warp/ -name "*.md" -type f -print0)
    fi
    if [[ -f "CONTRIBUTING.md" ]]; then
        doc_files+=("CONTRIBUTING.md")
    fi
    
    for file in "${doc_files[@]}"; do
        if [[ -f "$file" && -w "$file" ]]; then
            # Look for version patterns and update them (conservatively)
            if grep -q "v[0-9]*\.[0-9]*\.[0-9]*" "$file"; then
                log_info "Version references found in $file (manual review recommended)"
            fi
        fi
    done
}

# Validate cross-references
validate_cross_references() {
    log_info "Validating cross-references between documents..."
    
    local broken_refs=0
    
    # Check internal markdown links
    local check_files=()
    if [[ -d "docs" ]]; then
        while IFS= read -r -d '' file; do
            check_files+=("$file")
        done < <(find docs/ -name "*.md" -type f -print0 2>/dev/null)
    fi
    if [[ -d ".warp" ]]; then
        while IFS= read -r -d '' file; do
            check_files+=("$file")
        done < <(find .warp/ -name "*.md" -type f -print0 2>/dev/null)
    fi
    if [[ -f "README.md" ]]; then
        check_files+=("README.md")
    fi
    if [[ -f "CONTRIBUTING.md" ]]; then
        check_files+=("CONTRIBUTING.md")
    fi
    
    for file in "${check_files[@]}"; do
        if [[ -f "$file" ]]; then
            # Create a temporary file without code blocks to avoid false positives
            local temp_file
            temp_file=$(mktemp)
            
            # Remove code blocks using awk to prevent regex patterns being treated as links
            awk '
                /^```/ { in_code = !in_code; next }
                !in_code { print }
            ' "$file" > "$temp_file"
            
            while IFS= read -r link; do
                local target
                target=$(echo "$link" | sed -n 's/.*](\([^)#]*\)).*/\1/p')
                
                # Skip external links
                if [[ "$target" =~ ^https?:// || "$target" =~ ^# || -z "$target" ]]; then
                    continue
                fi
                
                # Check if target exists
                if [[ ! -e "$target" ]]; then
                    log_error "Broken reference in $file: $target"
                    ((broken_refs++))
                fi
            done < <(grep -o '\[.*\]([^)]*\.md[^)]*)' "$temp_file" 2>/dev/null || true)
            
            rm -f "$temp_file"
        fi
    done
    
    if [[ $broken_refs -eq 0 ]]; then
        log_success "All cross-references are valid"
    else
        log_error "Found $broken_refs broken cross-references"
        return 1
    fi
}

# Validate executable consistency (from validate-structural-alignment.sh)
validate_executable_consistency() {
    log_info "Validating executable references consistency..."
    
    local inconsistencies=0
    
    # Check for incorrect .sh references in user-facing documentation
    local readme_file="README.md"
    if [[ -f "$readme_file" ]]; then
        # Look for soft-delete.sh references that should be just soft-delete
        while IFS= read -r line; do
            # Skip lines that clearly refer to source code or development
            if [[ "$line" =~ (source|repository|development|clone|git|\.sh.*#) ]]; then
                continue
            fi
            
            # Check for .sh usage in examples or commands
            if [[ "$line" =~ soft-delete\.sh[[:space:]] ]]; then
                log_warning "Potential .sh usage in user example in $readme_file: $line"
            fi
        done < <(grep "soft-delete\.sh" "$readme_file" 2>/dev/null || true)
    fi
    
    # Check docs and examples directories
    for dir in docs examples; do
        if [[ -d "$dir" ]]; then
            for file in "$dir"/*.md; do
                if [[ -f "$file" ]]; then
                    # Look for soft-delete.sh references that should be just soft-delete
                    while IFS= read -r line; do
                        # Skip lines that clearly refer to source code or development
                        if [[ "$line" =~ (source|repository|development|clone|git|\.sh.*#) ]]; then
                            continue
                        fi
                        
                        # Check for .sh usage in examples or commands
                        if [[ "$line" =~ soft-delete\.sh[[:space:]] ]]; then
                            log_warning "Potential .sh usage in user example in $file: $line"
                        fi
                    done < <(grep "soft-delete\.sh" "$file" 2>/dev/null || true)
                fi
            done
        fi
    done
    
    # Validate installation path consistency
    local install_paths=()
    while IFS= read -r path; do
        install_paths+=("$path")
    done < <(grep -o '/usr/local/bin/[a-zA-Z0-9_-]*' README.md docs/*.md 2>/dev/null || true)
    
    # Check that all installation paths are consistent
    local expected_path="/usr/local/bin/soft-delete"
    for path in "${install_paths[@]}"; do
        if [[ "$path" != "$expected_path" ]]; then
            log_error "Inconsistent installation path: $path (expected: $expected_path)"
            inconsistencies=$((inconsistencies + 1))
        fi
    done
    
    if [[ $inconsistencies -eq 0 ]]; then
        log_success "Executable references: All references are consistent"
        return 0
    else
        log_error "Executable references: $inconsistencies inconsistencies found"
        return 1
    fi
}

# Validate script documentation coverage (from validate-structural-alignment.sh)
validate_script_documentation() {
    log_info "Validating script documentation coverage..."
    
    local undocumented_scripts=0
    
    # Check if all scripts are documented
    if [[ -d "scripts" ]]; then
        for script in scripts/*.sh; do
            if [[ -f "$script" ]]; then
                local script_name
                script_name=$(basename "$script")
                
                # Check if script is mentioned in API docs
                if [[ -f "docs/API.md" ]]; then
                    if ! grep -q "$script_name" "docs/API.md"; then
                        log_warning "Script not documented in API.md: $script_name"
                        undocumented_scripts=$((undocumented_scripts + 1))
                    fi
                fi
            fi
        done
    fi
    
    if [[ $undocumented_scripts -eq 0 ]]; then
        log_success "Script documentation: All scripts are documented"
        return 0
    else
        log_warning "Script documentation: $undocumented_scripts scripts may need documentation"
        return 0  # Don't fail on this, just warn
    fi
}

# Comprehensive validation function
run_comprehensive_validation() {
    log_info "Running comprehensive structural validation..."
    
    local validation_failed=0
    
    # Run all validation checks
    if ! validate_cross_references; then
        validation_failed=1
    fi
    
    if ! validate_executable_consistency; then
        validation_failed=1
    fi
    
    if ! validate_script_documentation; then
        validation_failed=1
    fi
    
    if [[ $validation_failed -eq 0 ]]; then
        log_success "🎉 All comprehensive validation checks passed!"
        return 0
    else
        log_error "❌ Some validation checks failed"
        return 1
    fi
}

# Final verification after synchronization
final_verification() {
    log_info "Running final verification for duplicate prevention..."
    
    local verification_failed=0
    local docs_to_check=(
        "README.md"
        ".warp/project-context.md"
    )
    
    for doc in "${docs_to_check[@]}"; do
        if [[ -f "$doc" ]]; then
            log_info "Checking $doc for duplicates..."
            
            # Check for duplicates
        check_for_duplicates "$doc"
            local duplicate_check=$?
            if [[ $duplicate_check -ne 0 ]]; then
                log_error "VERIFICATION FAILED: Duplicates detected in $doc after synchronization"
                verification_failed=1
            else
                log_success "$doc is clean - no duplicates detected"
            fi
            
            # Verify structure sections are properly formatted
            local structure_blocks
            structure_blocks=$(grep -c '^```$' "$doc" 2>/dev/null || echo 0)
            if [[ $structure_blocks -gt 0 && $((structure_blocks % 2)) -ne 0 ]]; then
                log_error "VERIFICATION FAILED: Unmatched code blocks in $doc"
                verification_failed=1
            fi
        fi
    done
    
    if [[ $verification_failed -eq 0 ]]; then
        log_success "🎉 Final verification passed - no duplicates detected!"
        return 0
    else
        log_error "❌ Final verification failed - duplicates or formatting issues detected"
        return 1
    fi
}

# Main synchronization function
sync_all_documentation() {
    log_info "Starting comprehensive documentation synchronization..."
    
    # First, generate or update the canonical PROJECT-STRUCTURE.md
    generate_project_structure_file
    
    # Update project structure in key documents (but NOT API.md)
    local docs_to_update=(
        "README.md"
        ".warp/project-context.md"
    )
    
    for doc in "${docs_to_update[@]}"; do
        if [[ -f "$doc" ]]; then
            update_file_listings "$doc"
            update_script_references "$doc"
        fi
    done
    
    # Preserve existing API documentation (do not regenerate)
    preserve_api_docs
    
    # Sync version references
    sync_version_references
    
    # Validate all cross-references
    validate_cross_references
    
    # Final verification to ensure no duplicates were created
    final_verification
    
    log_success "Documentation synchronization complete!"
}

# Command line interface
case "${1:-sync}" in
    --generate-structure-file)
        generate_project_structure_file
        ;;
    --generate-tree)
        generate_directory_tree
        ;;
    --clean-duplicates)
        log_info "Cleaning duplicates from documentation files..."
        for doc in "README.md" ".warp/project-context.md"; do
            if [[ -f "$doc" ]]; then
                if ! check_for_duplicates "$doc"; then
                    clean_duplicates "$doc"
                else
                    log_success "$doc is already clean"
                fi
            fi
        done
        log_success "Duplicate cleaning completed"
        ;;
    --check-duplicates)
        log_info "Checking for duplicates in documentation files..."
        found_duplicates=0
        for doc in "README.md" ".warp/project-context.md"; do
            if [[ -f "$doc" ]]; then
                if ! check_for_duplicates "$doc"; then
                    found_duplicates=1
                fi
            fi
        done
        if [[ $found_duplicates -eq 0 ]]; then
            log_success "No duplicates found in any documentation files"
        else
            log_error "Duplicates found - run with --clean-duplicates to fix"
            exit 1
        fi
        ;;
    --validate-only)
        validate_cross_references
        ;;
    --validate-comprehensive)
        run_comprehensive_validation
        ;;
    --validate-executables)
        validate_executable_consistency
        ;;
    --validate-script-docs)
        validate_script_documentation
        ;;
    --preserve-api)
        preserve_api_docs
        ;;
    --version-sync)
        sync_version_references
        ;;
    --verify)
        final_verification
        ;;
    sync|--sync|*)
        sync_all_documentation
        ;;
esac
