#!/bin/bash
# Structural Synchronization Tool
# Automatically updates documentation to match current repository structure

set -euo pipefail

# Script directory detection
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$REPO_ROOT"

# Utility functions
log_info() {
    echo "ℹ️  $*"
}

log_success() {
    echo "✅ $*"
}

log_error() {
    echo "❌ $*" >&2
}

log_warning() {
    echo "⚠️  $*" >&2
}

# Only show header when running as main script (not when generating tree)
if [[ "${1:-sync}" != "--generate-tree" ]]; then
    echo "🔄 REPOSITORY STRUCTURE SYNCHRONIZATION"
    echo "========================================"
fi

# Generate comprehensive PROJECT-STRUCTURE.md file
generate_project_structure_file() {
    local structure_file="$REPO_ROOT/docs/PROJECT-STRUCTURE.md"
    local timestamp
    timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
    
    log_info "Generating canonical PROJECT-STRUCTURE.md file..."
    
    cat > "$structure_file" << 'EOF'
# Project Structure

> **Single Source of Truth**: This file is the canonical reference for the soft-delete project structure. All documentation structure sections are synchronized from this file.
> 
> **Auto-generated by sync-structure.sh** - Do not edit manually. Changes will be overwritten during synchronization.

## Directory Tree

EOF
    
    # Generate the tree structure
    generate_directory_tree >> "$structure_file"
    
    cat >> "$structure_file" << 'EOF'

## Structure Guidelines

### File Organization Principles

1. **Configuration at Root**: Primary configuration files (`.editorconfig`, `.gitignore`, etc.) remain at project root
2. **Documentation Hierarchy**: 
   - Technical docs in `docs/` directory
   - Warp AI context in `.warp/` directory
   - Project overview in root `README.md`
3. **Script Organization**: All utility scripts in `scripts/` directory with clear naming
4. **Test Structure**: All tests in `tests/` directory using BATS framework
5. **Build Artifacts**: Compiled binaries in `bin/`, distribution files in `dist/`

### Directory Purposes

- **`.github/`**: GitHub-specific configuration and workflows
- **`.warp/`**: AI agent configuration and development protocols
- **`bin/`**: Compiled executable binaries
- **`docs/`**: Comprehensive technical documentation
- **`examples/`**: Usage examples and demonstrations
- **`scripts/`**: Development and maintenance utilities
- **`tests/`**: Test suites and testing infrastructure

### Validation Requirements

- All scripts must be documented in API.md
- Cross-references must be valid and up-to-date
- File counts must match actual repository state
- Executable references must use correct naming conventions

EOF
    
    echo "*Last Updated: $timestamp*" >> "$structure_file"
    
    log_success "Generated PROJECT-STRUCTURE.md with $(wc -l < "$structure_file") lines"
    return 0
}

# Generate complete directory tree showing ALL files and directories for transparency
generate_directory_tree() {
    # Generate complete tree structure for full transparency
    echo '```'
    echo "soft-delete/"
    
    # First pass: generate tree without comments to find the longest line
    local tree_lines=()
    while IFS= read -r line; do
        tree_lines+=("$line")
    done < <(generate_complete_tree_structure "." "" "false" "no-comments")
    
    # Find the longest line length
    local max_length=0
    for line in "${tree_lines[@]}"; do
        local line_length=${#line}
        if [[ $line_length -gt $max_length ]]; then
            max_length=$line_length
        fi
    done
    
    # Set global alignment column (longest line + minimum 2 spaces)
    GLOBAL_COMMENT_COLUMN=$((max_length + 2))
    
    # Second pass: generate tree with comments aligned to the calculated column
    generate_complete_tree_structure "." "" "false" "with-comments"
    
    echo '```'
}

# Helper function to recursively generate complete tree structure
generate_complete_tree_structure() {
    local current_dir="$1"
    local prefix="$2"
    local is_last="$3"
    local comment_mode="${4:-with-comments}"  # Default to with-comments for backward compatibility
    
    # Skip .git directory for readability but include everything else
    if [[ "$(basename "$current_dir")" == ".git" ]]; then
        return
    fi
    
    # Get all entries (files and directories) sorted
    local entries=()
    while IFS= read -r -d '' entry; do
        entries+=("$entry")
    done < <(find "$current_dir" -maxdepth 1 -mindepth 1 ! -name ".git" -print0 | sort -z)
    
    local entry_count=${#entries[@]}
    local current_index=0
    
    for entry in "${entries[@]}"; do
        current_index=$((current_index + 1))
        local basename_entry
        basename_entry=$(basename "$entry")
        local is_last_entry="false"
        
        if [[ $current_index -eq $entry_count ]]; then
            is_last_entry="true"
        fi
        
        # Determine tree characters
        local tree_char="├──"
        local next_prefix="$prefix│   "
        
        if [[ "$is_last_entry" == "true" ]]; then
            tree_char="└──"
            next_prefix="$prefix    "
        fi
        
        if [[ -d "$entry" ]]; then
            # Handle directory
            local tree_line="$prefix$tree_char $basename_entry/"
            if [[ "$comment_mode" == "no-comments" ]]; then
                echo "$tree_line"
            else
                # Generate description for directories
                local description
                description=$(generate_file_description "$entry" "$prefix$tree_char " "$comment_mode")
                echo "$tree_line$description"
            fi
            # Recursively process subdirectory
            generate_complete_tree_structure "$entry" "$next_prefix" "$is_last_entry" "$comment_mode"
        else
            # Handle file
            local tree_line="$prefix$tree_char $basename_entry"
            if [[ "$comment_mode" == "no-comments" ]]; then
                echo "$tree_line"
            else
                # Generate description for files
                local description
                description=$(generate_file_description "$entry" "$prefix$tree_char " "$comment_mode")
                echo "$tree_line$description"
            fi
        fi
    done
}

# Generate intelligent descriptions for files and directories with proper alignment
generate_file_description() {
    local entry="$1"
    local prefix="$2"
    local comment_mode="${3:-with-comments}"  # New parameter for comment mode
    local basename_entry
    basename_entry=$(basename "$entry")
    local description=""
    
    # Skip description generation if in no-comments mode
    if [[ "$comment_mode" == "no-comments" ]]; then
        echo ""
        return
    fi
    
    # Calculate the total length of the tree structure line up to the filename
    local tree_part="$prefix"
    if [[ -d "$entry" ]]; then
        tree_part="${tree_part}${basename_entry}/"
    else
        tree_part="${tree_part}${basename_entry}"
    fi
    
    # Use global alignment column if available, otherwise fall back to default
    local target_column=${GLOBAL_COMMENT_COLUMN:-40}
    local current_length=${#tree_part}
    local padding_needed=$((target_column - current_length))
    
    # Ensure minimum spacing
    if [[ $padding_needed -lt 2 ]]; then
        padding_needed=2
    fi
    
    # Generate padding spaces
    local padding
    padding=$(printf "%*s" $padding_needed "")
    
    # Directory descriptions
    if [[ -d "$entry" ]]; then
        case "$basename_entry" in
            ".github") description="${padding}# GitHub configuration and workflows" ;;
            "workflows") description="${padding}# GitHub Actions workflows" ;;
            ".githooks") description="${padding}# Git hooks for development workflow" ;;
            ".warp") description="${padding}# Warp.dev AI configuration and context" ;;
            "protocols") description="${padding}# Development protocols and procedures" ;;
            "rules") description="${padding}# AI agent behavioral rules" ;;
            "templates") description="${padding}# Template files for rules and protocols" ;;
            "bin") description="${padding}# Compiled executable binaries" ;;
            "dist") description="${padding}# Distribution and build artifacts" ;;
            "docs") description="${padding}# Comprehensive project documentation" ;;
            "examples") description="${padding}# Usage examples and demonstrations" ;;
            "Formula") description="${padding}# Package manager formulas (Homebrew)" ;;
            "reports") description="${padding}# Test reports and analysis artifacts" ;;
            "artifacts") description="${padding}# Build and test artifacts" ;;
            "coverage") description="${padding}# Test coverage reports" ;;
            "junit") description="${padding}# JUnit test result files" ;;
            "tap") description="${padding}# TAP (Test Anything Protocol) output" ;;
            "scripts") description="${padding}# Utility and automation scripts" ;;
            "tests") description="${padding}# Test suites and testing infrastructure" ;;
            *) description="" ;;
        esac
    else
        # File descriptions based on extension and name
        case "$basename_entry" in
            # Configuration files
            ".editorconfig") description="${padding}# Code formatting and editor standards" ;;
            ".gitattributes") description="${padding}# Git file handling configuration" ;;
            ".gitignore") description="${padding}# Git ignore patterns and exclusions" ;;
            ".markdownlint.yaml") description="${padding}# Markdown linting rules and configuration" ;;
            ".shellcheckrc") description="${padding}# Shell script linting configuration" ;;
            
            # GitHub workflows and hooks
            "release.yml") description="${padding}# GitHub Actions CI/CD release pipeline" ;;
            "pre-commit") description="${padding}# Git pre-commit hook executable" ;;
            
            # Documentation files
            "README.md") description="${padding}# Project overview and main documentation" ;;
            "API.md") description="${padding}# Comprehensive API reference documentation" ;;
            "DEPLOYMENT.md") description="${padding}# Deployment procedures and automation guide" ;;
            "PROJECT-STRUCTURE.md") description="${padding}# Canonical project structure documentation" ;;
            "SECURITY.md") description="${padding}# Security policies and vulnerability reporting" ;;
            "TESTING.md") description="${padding}# Testing procedures and infrastructure guide" ;;
            "CHANGELOG.md") description="${padding}# Version history and change tracking" ;;
            "CONTRIBUTING.md") description="${padding}# Contribution guidelines and development setup" ;;
            "project-context.md") description="${padding}# Main project context for AI assistance" ;;
            
            # Container and deployment files
            "docker-compose.test.yml") description="${padding}# Docker testing environment configuration" ;;
            "Dockerfile.runtime") description="${padding}# Runtime container image definition" ;;
            "Dockerfile.test") description="${padding}# Testing container image definition" ;;
            
            # Build and automation files
            "Makefile") description="${padding}# Build automation and development tasks" ;;
            "install.sh") description="${padding}# Installation script for end users" ;;
            
            # Legal and version files
            "LICENSE") description="${padding}# MIT License terms and conditions" ;;
            "VERSION") description="${padding}# Current version information" ;;
            
            # Main application files
            "soft-delete.sh") description="${padding}# Main application source script" ;;
            "soft-delete") description="${padding}# Compiled executable binary" ;;
            "soft-delete.rb") description="${padding}# Homebrew formula for package distribution" ;;
            
            # Utility script files (with specific descriptions)
            "benchmark.sh") description="${padding}# Performance testing and benchmarking" ;;
            "changelog.sh") description="${padding}# Automated changelog generation" ;;
            "check-duplicates.sh") description="${padding}# Duplicate content detection and cleanup" ;;
            "checkpoint.sh") description="${padding}# Development checkpoint and backup utility" ;;
            "cleanup.sh") description="${padding}# Comprehensive system cleanup utility" ;;
            "compliance-check.sh") description="${padding}# 100% compliance verification system" ;;
            "deploy.sh") description="${padding}# Deployment automation and orchestration" ;;
            "pre-commit-hook.sh") description="${padding}# Git pre-commit validation hook" ;;
            "quick-commit.sh") description="${padding}# Quick commit workflow automation" ;;
            "run-tests.sh") description="${padding}# Docker-based comprehensive test runner" ;;
            "security-scan.sh") description="${padding}# Security vulnerability scanning" ;;
            "setup-hooks.sh") description="${padding}# Git hooks installation and setup" ;;
            "sync-structure.sh") description="${padding}# Project structure synchronization" ;;
            "validate-structure.sh") description="${padding}# Project structure validation" ;;
            "version.sh") description="${padding}# Version management and tagging" ;;
            
            # Test files
            "edge-cases.bats") description="${padding}# Edge case and boundary testing suite" ;;
            "soft-delete.bats") description="${padding}# Main application test suite" ;;
            "test_helper.bash") description="${padding}# Test utilities and helper functions" ;;
            
            # Example files
            "basic_usage.sh") description="${padding}# Basic usage examples and tutorials" ;;
            "advanced_usage.sh") description="${padding}# Advanced integration examples" ;;
            
            # Hidden and marker files
            ".gitkeep") description="${padding}# Git directory preservation marker" ;;
            
            # Protocol and rule files (dynamically described by path)
            *.md)
                if [[ "$entry" == *"/protocols/"* ]]; then
                    description="${padding}# Development protocol specification"
                elif [[ "$entry" == *"/rules/"* ]]; then
                    description="${padding}# AI agent behavioral rule definition"
                elif [[ "$entry" == *"/templates/"* ]]; then
                    description="${padding}# Template for creating new rules"
                else
                    description="${padding}# Markdown documentation file"
                fi
                ;;
            
            # Programming and config files by extension
            *.sh)
                if [[ "$entry" == *"/rules/"* ]]; then
                    description="${padding}# AI response validation script"
                else
                    description="${padding}# Shell script"
                fi
                ;;
            *.py) description="${padding}# Python script" ;;
            *.js) description="${padding}# JavaScript file" ;;
            *.ts) description="${padding}# TypeScript file" ;;
            *.json) description="${padding}# JSON configuration or data file" ;;
            *.yaml|*.yml) description="${padding}# YAML configuration file" ;;
            *.toml) description="${padding}# TOML configuration file" ;;
            *.xml) description="${padding}# XML data or configuration file" ;;
            
            # Default for unknown files
            *) 
                if [[ -x "$entry" ]]; then
                    description="${padding}# Executable file"
                else
                    description=""
                fi
                ;;
        esac
    fi
    
    echo "$description"
}

# Check for duplicate structure sections
check_for_duplicates() {
    local file="$1"
    local duplicates=0
    
    # Count occurrences of structure indicators (specifically in code blocks)
    local structure_count=0
    if [[ -f "$file" ]]; then
        # Use a more robust approach that avoids potential stdin issues
        # Count occurrences of "soft-delete/" that appear to be project roots
        structure_count=$(awk '
            /^```/ { in_code = !in_code; next }
            in_code && /^soft-delete\/$/ { count++ }
            END { print count + 0 }
        ' "$file")
        
        # Check for multiple code blocks with soft-delete/ as project root
        if [[ ${structure_count:-0} -gt 1 ]]; then
            log_error "DUPLICATE DETECTED: Found $structure_count structure sections in $file"
            duplicates=$structure_count
        fi
    fi
    
    # Check for sync header duplication
    local header_count=0
    if grep -q "🔄 REPOSITORY STRUCTURE SYNCHRONIZATION" "$file" 2>/dev/null; then
        header_count=$(grep -c "🔄 REPOSITORY STRUCTURE SYNCHRONIZATION" "$file" 2>/dev/null)
        log_error "SYNC HEADER CONTAMINATION: Found sync headers in $file (should not exist)"
        duplicates=$((duplicates + header_count))
    fi
    
    if [[ $duplicates -gt 0 ]]; then
        return 1
    else
        return 0
    fi
}

# Clean existing duplicate structures
clean_duplicates() {
    local file="$1"
    local temp_file
    temp_file=$(mktemp)
    
    log_info "Cleaning any existing duplicates in $file..."
    
    # Remove sync headers that shouldn't be in the file
    sed '/🔄 REPOSITORY STRUCTURE SYNCHRONIZATION/d; /========================================/d' "$file" > "$temp_file"
    mv "$temp_file" "$file"
    
    # Remove duplicate structure sections (keep only the first one)
    local temp_file2
    temp_file2=$(mktemp)
    
    awk '
    BEGIN { structure_found = 0; in_structure = 0; skip_structure = 0 }
    
    # Detect start of structure section
    /^#+ (Project|Directory) Structure$/ {
        if (structure_found == 0) {
            structure_found = 1
            print $0
            next
        } else {
            # This is a duplicate - skip entire section
            skip_structure = 1
            next
        }
    }
    
    # Handle content within structure sections
    structure_found == 1 && !skip_structure {
        if (/^```/) {
            if (in_structure == 0) {
                in_structure = 1
                print $0
                next
            } else {
                in_structure = 0
                structure_found = 2  # Mark as completed
                print $0
                next
            }
        }
        if (in_structure == 1 || /^$/) {
            print $0
            next
        }
        if (/^#+ /) {
            structure_found = 2  # End of structure section
            print $0
            next
        }
        print $0
        next
    }
    
    # Skip duplicate structure content
    skip_structure == 1 {
        if (/^#+ / && !/^#+ (Project|Directory) Structure$/) {
            skip_structure = 0
            print $0
        }
        next
    }
    
    # Print all other lines
    { print }
    ' "$file" > "$temp_file2"
    
    mv "$temp_file2" "$file"
    log_success "Cleaned duplicates from $file"
}

# Update file listings in documentation using canonical source
update_file_listings() {
    local file="$1"
    local structure_file="$REPO_ROOT/docs/PROJECT-STRUCTURE.md"
    local temp_file
    temp_file=$(mktemp)
    
    log_info "Updating file listings in $file using canonical source..."
    
    # Ensure PROJECT-STRUCTURE.md exists and is up-to-date
    if [[ ! -f "$structure_file" ]]; then
        log_warning "PROJECT-STRUCTURE.md not found, generating it first"
        generate_project_structure_file
    fi
    
    # Skip duplicate checking for now to avoid hanging
    # TODO: Fix check_for_duplicates function separately
    
    # Extract just the tree structure from PROJECT-STRUCTURE.md
    local canonical_tree
    canonical_tree=$(sed -n '/^```$/,/^```$/p' "$structure_file")
    
    # Look for sections that need updating
    if grep -q "### Project Structure\|## Project Structure\|# Project Structure" "$file"; then
        
        # Use simple awk approach that we know works
        local temp_canonical
        temp_canonical=$(mktemp)
        
        # Write canonical tree to temp file
        echo "$canonical_tree" > "$temp_canonical"
        
        # Use awk to replace structure sections (same logic as before but simplified)
        awk -v canonical_file="$temp_canonical" '
        BEGIN {
            # Read canonical tree
            canonical_tree = ""
            while ((getline line < canonical_file) > 0) {
                canonical_tree = canonical_tree line "\n"
            }
            close(canonical_file)
            gsub(/\n$/, "", canonical_tree)
            skip_until_next_section = 0
        }
        
        # Detect structure section headers
        /^#{1,6}[ \t]+(Project|Directory)[ \t]+Structure[ \t]*$/ {
            print $0  # Print the header
            print ""  # Print blank line
            print canonical_tree  # Print canonical structure
            skip_until_next_section = 1
            next
        }
        
        # Skip content until next section when in replacement mode
        skip_until_next_section == 1 {
            # Look for next markdown header or end of file
            if (/^#{1,6}[ \t]+/ && !/^#{1,6}[ \t]+(Project|Directory)[ \t]+Structure[ \t]*$/) {
                skip_until_next_section = 0
                print $0
            }
            # Skip everything else until next section
            next
        }
        
        # Print all other lines
        { print }
        ' "$file" > "$temp_file"
        
        # Clean up temp files
        rm -f "$temp_canonical"
        
        if [[ -s "$temp_file" ]]; then
            mv "$temp_file" "$file"
            log_success "Updated structure in $file from canonical source"
        else
            rm "$temp_file"
            log_error "Failed to update $file - temp file is empty"
            return 1
        fi
    else
        rm -f "$temp_file"
        log_info "No structure sections found in $file to update"
    fi
}

# Update script references in documentation
update_script_references() {
    local file="$1"
    local temp_file
    temp_file=$(mktemp)
    
    log_info "Validating script references in $file..."
    
    # Find all script references and check if they exist
    local script_refs
    script_refs=$(grep -o 'scripts/[a-zA-Z0-9_-]*\.sh' "$file" 2>/dev/null || true)
    
    local updates_needed=false
    if [[ -n "$script_refs" ]]; then
        while IFS= read -r script_ref; do
            if [[ ! -f "$script_ref" ]]; then
                log_warning "Referenced script missing: $script_ref"
                updates_needed=true
            fi
        done <<< "$script_refs"
    fi
    
    if [[ "$updates_needed" == "true" ]]; then
        log_warning "Script references in $file need manual review"
    fi
    
    rm -f "$temp_file"
}

# Preserve existing API documentation (do not regenerate)
preserve_api_docs() {
    log_info "Preserving existing API documentation..."
    
    if [[ -f "docs/API.md" ]]; then
        log_success "API documentation exists and is preserved"
        log_info "Note: API.md contains comprehensive technical documentation"
        log_info "      and should be manually maintained by developers"
    else
        log_warning "API documentation file (docs/API.md) not found"
        log_info "Consider creating comprehensive API documentation"
    fi
}

# Update version references across all files
sync_version_references() {
    if [[ ! -f "VERSION" ]]; then
        log_warning "VERSION file not found, skipping version sync"
        return 0
    fi
    
    local version
    version=$(tr -d '\n\r' < VERSION | tr -d ' ')
    
    log_info "Synchronizing version $version across all files..."
    
    # Update README.md badge
    if [[ -f "README.md" ]]; then
        if grep -q "badge/version-" "README.md"; then
            sed -i "s|badge/version-[^-]*-blue|badge/version-$version-blue|g" "README.md"
            log_success "Updated version badge in README.md"
        fi
    fi
    
    # Update other version references as needed
    local doc_files=()
    if [[ -d "docs" ]]; then
        while IFS= read -r -d '' file; do
            doc_files+=("$file")
        done < <(find docs/ -name "*.md" -type f -print0)
    fi
    if [[ -d ".warp" ]]; then
        while IFS= read -r -d '' file; do
            doc_files+=("$file")
        done < <(find .warp/ -name "*.md" -type f -print0)
    fi
    if [[ -f "CONTRIBUTING.md" ]]; then
        doc_files+=("CONTRIBUTING.md")
    fi
    
    for file in "${doc_files[@]}"; do
        if [[ -f "$file" && -w "$file" ]]; then
            # Look for version patterns and update them (conservatively)
            if grep -q "v[0-9]*\.[0-9]*\.[0-9]*" "$file"; then
                log_info "Version references found in $file (manual review recommended)"
            fi
        fi
    done
}

# Validate cross-references
validate_cross_references() {
    log_info "Validating cross-references between documents..."
    
    local broken_refs=0
    
    # Check internal markdown links
    local check_files=()
    if [[ -d "docs" ]]; then
        while IFS= read -r -d '' file; do
            check_files+=("$file")
        done < <(find docs/ -name "*.md" -type f -print0 2>/dev/null)
    fi
    if [[ -d ".warp" ]]; then
        while IFS= read -r -d '' file; do
            check_files+=("$file")
        done < <(find .warp/ -name "*.md" -type f -print0 2>/dev/null)
    fi
    if [[ -f "README.md" ]]; then
        check_files+=("README.md")
    fi
    if [[ -f "CONTRIBUTING.md" ]]; then
        check_files+=("CONTRIBUTING.md")
    fi
    
    for file in "${check_files[@]}"; do
        if [[ -f "$file" ]]; then
            # Create a temporary file without code blocks to avoid false positives
            local temp_file
            temp_file=$(mktemp)
            
            # Remove code blocks using awk to prevent regex patterns being treated as links
            awk '
                /^```/ { in_code = !in_code; next }
                !in_code { print }
            ' "$file" > "$temp_file"
            
            while IFS= read -r link; do
                local target
                target=$(echo "$link" | sed -n 's/.*](\([^)#]*\)).*/\1/p')
                
                # Skip external links
                if [[ "$target" =~ ^https?:// || "$target" =~ ^# || -z "$target" ]]; then
                    continue
                fi
                
                # Check if target exists
                if [[ ! -e "$target" ]]; then
                    log_error "Broken reference in $file: $target"
                    ((broken_refs++))
                fi
            done < <(grep -o '\[.*\]([^)]*\.md[^)]*)' "$temp_file" 2>/dev/null || true)
            
            rm -f "$temp_file"
        fi
    done
    
    if [[ $broken_refs -eq 0 ]]; then
        log_success "All cross-references are valid"
    else
        log_error "Found $broken_refs broken cross-references"
        return 1
    fi
}

# Validate executable consistency (from validate-structural-alignment.sh)
validate_executable_consistency() {
    log_info "Validating executable references consistency..."
    
    local inconsistencies=0
    
    # Check for incorrect .sh references in user-facing documentation
    local readme_file="README.md"
    if [[ -f "$readme_file" ]]; then
        # Look for soft-delete.sh references that should be just soft-delete
        while IFS= read -r line; do
            # Skip lines that clearly refer to source code, development, or installation instructions
            if [[ "$line" =~ (source|repository|development|clone|git|\.sh.*#|sudo.*cp.*soft-delete\.sh|Make.*changes.*to.*soft-delete\.sh) ]]; then
                continue
            fi
            
            # Check for .sh usage in examples or commands (but not installation steps)
            if [[ "$line" =~ soft-delete\.sh[[:space:]] ]]; then
                log_warning "Potential .sh usage in user example in $readme_file: $line"
            fi
        done < <(grep "soft-delete\.sh" "$readme_file" 2>/dev/null || true)
    fi
    
    # Check docs and examples directories
    for dir in docs examples; do
        if [[ -d "$dir" ]]; then
            for file in "$dir"/*.md; do
                if [[ -f "$file" ]]; then
                    # Look for soft-delete.sh references that should be just soft-delete
                    while IFS= read -r line; do
                        # Skip lines that clearly refer to source code or development
                        if [[ "$line" =~ (source|repository|development|clone|git|\.sh.*#) ]]; then
                            continue
                        fi
                        
                        # Check for .sh usage in examples or commands
                        if [[ "$line" =~ soft-delete\.sh[[:space:]] ]]; then
                            log_warning "Potential .sh usage in user example in $file: $line"
                        fi
                    done < <(grep "soft-delete\.sh" "$file" 2>/dev/null || true)
                fi
            done
        fi
    done
    
    # Validate installation path consistency
    local install_paths=()
    while IFS= read -r grep_output; do
        # Extract just the path part (after the colon if present)
        local path
        if [[ "$grep_output" == *:* ]]; then
            path="${grep_output#*:}"  # Remove filename prefix
        else
            path="$grep_output"
        fi
        install_paths+=("$path")
    done < <(grep -o '/usr/local/bin/[a-zA-Z0-9_-]*' README.md docs/*.md 2>/dev/null || true)
    
    # Check that all installation paths are consistent
    local expected_path="/usr/local/bin/soft-delete"
    for path in "${install_paths[@]}"; do
        # Skip empty paths or paths that are just "/usr/local/bin/"
        if [[ -z "$path" || "$path" == "/usr/local/bin/" ]]; then
            continue
        fi
        if [[ "$path" != "$expected_path" ]]; then
            log_error "Inconsistent installation path: $path (expected: $expected_path)"
            inconsistencies=$((inconsistencies + 1))
        fi
    done
    
    if [[ $inconsistencies -eq 0 ]]; then
        log_success "Executable references: All references are consistent"
        return 0
    else
        log_error "Executable references: $inconsistencies inconsistencies found"
        return 1
    fi
}

# Validate script documentation coverage (from validate-structural-alignment.sh)
validate_script_documentation() {
    log_info "Validating script documentation coverage..."
    
    local undocumented_scripts=0
    
    # Check if all scripts are documented
    if [[ -d "scripts" ]]; then
        for script in scripts/*.sh; do
            if [[ -f "$script" ]]; then
                local script_name
                script_name=$(basename "$script")
                
                # Check if script is mentioned in API docs
                if [[ -f "docs/API.md" ]]; then
                    if ! grep -q "$script_name" "docs/API.md"; then
                        log_warning "Script not documented in API.md: $script_name"
                        undocumented_scripts=$((undocumented_scripts + 1))
                    fi
                fi
            fi
        done
    fi
    
    if [[ $undocumented_scripts -eq 0 ]]; then
        log_success "Script documentation: All scripts are documented"
        return 0
    else
        log_warning "Script documentation: $undocumented_scripts scripts may need documentation"
        return 0  # Don't fail on this, just warn
    fi
}

# Comprehensive validation function
run_comprehensive_validation() {
    log_info "Running comprehensive structural validation..."
    
    local validation_failed=0
    
    # Run all validation checks
    if ! validate_cross_references; then
        validation_failed=1
    fi
    
    if ! validate_executable_consistency; then
        validation_failed=1
    fi
    
    if ! validate_script_documentation; then
        validation_failed=1
    fi
    
    if [[ $validation_failed -eq 0 ]]; then
        log_success "🎉 All comprehensive validation checks passed!"
        return 0
    else
        log_error "❌ Some validation checks failed"
        return 1
    fi
}

# Final verification after synchronization
final_verification() {
    log_info "Running final verification for duplicate prevention..."
    
    local verification_failed=0
    local docs_to_check=(
        "README.md"
        "CONTRIBUTING.md"
        ".warp/protocols/structural-alignment-protocol.md"
    )
    
    for doc in "${docs_to_check[@]}"; do
        if [[ -f "$doc" ]]; then
            log_info "Checking $doc for duplicates..."
            
            # Check for duplicates
        check_for_duplicates "$doc"
            local duplicate_check=$?
            if [[ $duplicate_check -ne 0 ]]; then
                log_error "VERIFICATION FAILED: Duplicates detected in $doc after synchronization"
                verification_failed=1
            else
                log_success "$doc is clean - no duplicates detected"
            fi
            
            # Verify code blocks are properly matched (total count should be even)
            local total_code_blocks
            total_code_blocks=$(grep -c '^```' "$doc" 2>/dev/null || echo 0)
            
            # Check if total code block count is even (each opening should have a closing)
            if [[ $total_code_blocks -gt 0 && $((total_code_blocks % 2)) -ne 0 ]]; then
                log_error "VERIFICATION FAILED: Unmatched code blocks in $doc (total: $total_code_blocks - should be even)"
                verification_failed=1
            fi
        fi
    done
    
    if [[ $verification_failed -eq 0 ]]; then
        log_success "🎉 Final verification passed - no duplicates detected!"
        return 0
    else
        log_error "❌ Final verification failed - duplicates or formatting issues detected"
        return 1
    fi
}

# Main synchronization function
sync_all_documentation() {
    log_info "Starting comprehensive documentation synchronization..."
    
    # First, generate or update the canonical PROJECT-STRUCTURE.md
    generate_project_structure_file
    
    # Update project structure in key documents (but NOT API.md)
    local docs_to_update=(
        "README.md"
        "CONTRIBUTING.md"
        ".warp/protocols/structural-alignment-protocol.md"
    )
    
    for doc in "${docs_to_update[@]}"; do
        if [[ -f "$doc" ]]; then
            update_file_listings "$doc"
            update_script_references "$doc"
        fi
    done
    
    # Preserve existing API documentation (do not regenerate)
    preserve_api_docs
    
    # Sync version references
    sync_version_references
    
    # Validate all cross-references
    validate_cross_references
    
    # Final verification to ensure no duplicates were created
    final_verification
    
    log_success "Documentation synchronization complete!"
}

# Command line interface
case "${1:-sync}" in
    --generate-structure-file)
        generate_project_structure_file
        ;;
    --generate-tree)
        generate_directory_tree
        ;;
    --clean-duplicates)
        log_info "Cleaning duplicates from documentation files..."
        for doc in "README.md" "CONTRIBUTING.md" ".warp/protocols/structural-alignment-protocol.md"; do
            if [[ -f "$doc" ]]; then
                if ! check_for_duplicates "$doc"; then
                    clean_duplicates "$doc"
                else
                    log_success "$doc is already clean"
                fi
            fi
        done
        log_success "Duplicate cleaning completed"
        ;;
    --check-duplicates)
        log_info "Checking for duplicates in documentation files..."
        found_duplicates=0
        for doc in "README.md" "CONTRIBUTING.md" ".warp/protocols/structural-alignment-protocol.md"; do
            if [[ -f "$doc" ]]; then
                if ! check_for_duplicates "$doc"; then
                    found_duplicates=1
                fi
            fi
        done
        if [[ $found_duplicates -eq 0 ]]; then
            log_success "No duplicates found in any documentation files"
        else
            log_error "Duplicates found - run with --clean-duplicates to fix"
            exit 1
        fi
        ;;
    --validate-only)
        validate_cross_references
        ;;
    --validate-comprehensive)
        run_comprehensive_validation
        ;;
    --validate-executables)
        validate_executable_consistency
        ;;
    --validate-script-docs)
        validate_script_documentation
        ;;
    --preserve-api)
        preserve_api_docs
        ;;
    --version-sync)
        sync_version_references
        ;;
    --verify)
        final_verification
        ;;
    sync|--sync|*)
        sync_all_documentation
        ;;
esac
